### ISSUE TITLE
UnsupportedAudioFileException?

### ISSUE THREAD

**Issue by bwang482** [ahmetaa/lium-diarization#1]
Thanks for making it work in Java 1.8! Unfortunately I have not managed to get it working on my machine. 

```
Processing ./test_wav/t001.wav
t001
#####################################################
#   t001
#####################################################
compute the MFCC
07:36.274                CONFIG| cmdLine: --help --fInputMask=./test_wav/t001.wav --fInputDesc=audio16kHz2sphinx,1:1:0:0:0:0,13,0:0:0 --fOutputMask=././test_out//t001/%s.mfcc --fOutputDesc=sphinx,1:1:0:0:0:0,13,0:0:0 t001
07:36.274                CONFIG|  ======================================================
07:36.274                CONFIG| Program name = Wave2FeatureSet
07:36.274                CONFIG|  ------------------------------------------------------
07:36.274                CONFIG| [options] show:t001
07:36.274                CONFIG| --fInputMask 	 Input featureSet: mask = ./test_wav/t001.wav [fr.lium.spkDiarization.parameter.ParameterAudioInputFeature]
07:36.275                CONFIG| --fInputDesc 	 Input featureSet: description (type[:deltatype][,s:e:ds:de:dds:dde,dim,c:r:wSize:method]) = audio16kHz2sphinx:sphinx,1:1:0:0:0:0,13,0:0:0:0 [fr.lium.spkDiarization.parameter.ParameterAudioInputFeature]
07:36.275                CONFIG| 	 	 type [spro4,htk,sphinx,gztxt,featureSetTransformation,audio8kHz2sphinx,audio16kHz2sphinx,audio22kHz2sphinx,audio44kHz2sphinx,audio48kHz2sphinx] = audio16kHz2sphinx (6)
07:36.275                CONFIG| 	 	 deltaType [spro4,htk,sphinx] = sphinx (2)
07:36.275                CONFIG| 	 	 static [0=not present,1=present ,3=to be removed] = 1
07:36.275                CONFIG| 	 	 energy [0,1,3] = 1
07:36.275                CONFIG| 	 	 delta [0,1,2=computed on the fly,3] = 0
07:36.275                CONFIG| 	 	 delta energy [0,1,2=computed on the fly,3] = 0
07:36.275                CONFIG| 	 	 delta delta [0,1,2,3] = 0
07:36.276                CONFIG| 	 	 delta delta energy [0,1,2,3] = 0
07:36.276                CONFIG|  	 	 file dim = 13
07:36.276                CONFIG|  	 	 normalization, center [0,1] = 0
07:36.276                CONFIG|  	 	 normalization, reduce [0,1] = 0
07:36.276                CONFIG|  	 	 normalization, window size = 0
07:36.276                CONFIG| 	 	 normalization, method [0 (segment), 1 (cluster), 2 (sliding), 3 (warping)] =0
07:36.276                CONFIG| --fInputMemoryOccupationRate 	 Input featureSet: memory occupation rate of the feature in the java virtual machine = ./test_wav/t001.wav [fr.lium.spkDiarization.parameter.ParameterAudioInputFeature]
07:36.276                CONFIG| --fInputSpeechThr 	 Input featureSet: silence segmentation method [E,BIGAUSSIAN,None] = None(2) [fr.lium.spkDiarization.parameter.ParameterAudioInputFeature]
07:36.277                CONFIG| --fInputSpeechMethod 	 Input featureSet: silence segmentation method [E,BIGAUSSIAN,None] = None(2) [fr.lium.spkDiarization.parameter.ParameterAudioInputFeature]
07:36.277                CONFIG| --fOutputMask 	 Output featureSet: mask = ././test_out//t001/%s.mfcc [fr.lium.spkDiarization.parameter.ParameterAudioOutputFeature]
07:36.277                CONFIG| --fOutputDesc 	 Output featureSet: description (type[:deltatype][,s:e:ds:de:dds:dde,dim,c:r:wSize:method]) = sphinx:sphinx,1:1:0:0:0:0,13,0:0:0:0 [fr.lium.spkDiarization.parameter.ParameterAudioOutputFeature]
07:36.277                CONFIG| 	 	 type [spro4,htk,sphinx,gztxt,featureSetTransformation,audio8kHz2sphinx,audio16kHz2sphinx,audio22kHz2sphinx,audio44kHz2sphinx,audio48kHz2sphinx] = sphinx (2)
07:36.277                CONFIG| 	 	 deltaType [spro4,htk,sphinx] = sphinx (2)
07:36.277                CONFIG| 	 	 static [0=not present,1=present ,3=to be removed] = 1
07:36.277                CONFIG| 	 	 energy [0,1,3] = 1
07:36.277                CONFIG| 	 	 delta [0,1,2=computed on the fly,3] = 0
07:36.278                CONFIG| 	 	 delta energy [0,1,2=computed on the fly,3] = 0
07:36.278                CONFIG| 	 	 delta delta [0,1,2,3] = 0
07:36.278                CONFIG| 	 	 delta delta energy [0,1,2,3] = 0
07:36.278                CONFIG|  	 	 file dim = 13
07:36.278                CONFIG|  	 	 normalization, center [0,1] = 0
07:36.278                CONFIG|  	 	 normalization, reduce [0,1] = 0
07:36.278                CONFIG|  	 	 normalization, window size = 0
07:36.278                CONFIG| 	 	 normalization, method [0 (segment), 1 (cluster), 2 (sliding), 3 (warping)] =0
07:36.278                CONFIG| --fOutputMemoryOccupationRate 	 Output featureSet: memory occupation rate of the feature in the java virtual machine = ././test_out//t001/%s.mfcc [fr.lium.spkDiarization.parameter.ParameterAudioOutputFeature]
07:36.279                CONFIG|  ------------------------------------------------------
07:36.279                CONFIG| --sInputMask 	 Input segmentation file mask =  [fr.lium.spkDiarization.parameter.ParameterSegmentationInputFile]
07:36.279                CONFIG| --sInputFormat 	 Input segmentation file format = seg,ISO-8859-1 ([seg,bck,ctl,saus.seg,seg.xml,media.xml,repere.xml,eger.hyp], [ISO-8859-1,UTF8]) [fr.lium.spkDiarization.parameter.ParameterSegmentationInputFile]
07:36.279                CONFIG| --sInputRate 	 Input segmentation file rate = 100 [fr.lium.spkDiarization.parameter.ParameterSegmentationInputFile]
07:36.337 SEVERE AudioFeatureSetFa  UnsupportedAudioFileException
javax.sound.sampled.UnsupportedAudioFileException: file is not a supported file type
	at javax.sound.sampled.AudioSystem.getAudioFileFormat(AudioSystem.java:1078)
	at fr.lium.spkDiarization.libFeature.AudioFeatureSetFactory.getAudio(AudioFeatureSetFactory.java:162)
	at fr.lium.spkDiarization.libFeature.AudioFeatureSetFactory.MakeFeature(AudioFeatureSetFactory.java:207)
	at fr.lium.spkDiarization.libFeature.AudioFeatureSetFactory.MakeMFCCFeature(AudioFeatureSetFactory.java:255)
	at fr.lium.spkDiarization.libFeature.AudioFeatureSet.read(AudioFeatureSet.java:898)
	at fr.lium.spkDiarization.libFeature.AudioFeatureSet.setCurrentShow(AudioFeatureSet.java:1322)
	at fr.lium.spkDiarization.tools.Wave2FeatureSet.main(Wave2FeatureSet.java:53)
```

**Comment by bwang482** [comment]
Solved.
